/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ao.com.infox.telas;

import ao.com.infox.dal.ModuloConexao;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nelson Salvador
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    Connection conexao= null;
    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
        
        conexao = ModuloConexao.conector();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        desktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        mencad = new javax.swing.JMenu();
        mancadcli = new javax.swing.JMenuItem();
        mancados = new javax.swing.JMenuItem();
        mancadusu = new javax.swing.JMenuItem();
        menrel = new javax.swing.JMenu();
        manRelcli = new javax.swing.JMenuItem();
        manreser = new javax.swing.JMenuItem();
        menajusob = new javax.swing.JMenu();
        menusobre = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menOpcsai = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("X Sistema  para controle de ordem de serviço OS ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(645, 406));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ao/com/infox/icones/letra-x (1).png"))); // NOI18N

        lblusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblusuario.setText("Usuário");

        lbldata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldata.setText("Data");

        mencad.setText("Registar");
        mencad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadActionPerformed(evt);
            }
        });

        mancadcli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mancadcli.setText("Cliente");
        mancadcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mancadcliActionPerformed(evt);
            }
        });
        mencad.add(mancadcli);

        mancados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mancados.setText("OS");
        mancados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mancadosActionPerformed(evt);
            }
        });
        mencad.add(mancados);

        mancadusu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mancadusu.setText("Usuários");
        mancadusu.setEnabled(false);
        mancadusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mancadusuActionPerformed(evt);
            }
        });
        mencad.add(mancadusu);

        menu.add(mencad);

        menrel.setText("Relatório");
        menrel.setEnabled(false);
        menrel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menrelActionPerformed(evt);
            }
        });

        manRelcli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        manRelcli.setText("Clientes");
        manRelcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manRelcliActionPerformed(evt);
            }
        });
        menrel.add(manRelcli);

        manreser.setText("Serviços");
        manreser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manreserActionPerformed(evt);
            }
        });
        menrel.add(manreser);

        menu.add(menrel);

        menajusob.setText("Ajuda");

        menusobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        menusobre.setText("Sobre");
        menusobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusobreActionPerformed(evt);
            }
        });
        menajusob.add(menusobre);

        menu.add(menajusob);

        menOpc.setText("Opções");

        menOpcsai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menOpcsai.setText("Saír");
        menOpcsai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpcsaiActionPerformed(evt);
            }
        });
        menOpc.add(menOpcsai);

        menu.add(menOpc);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblusuario)
                            .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lblusuario)
                .addGap(18, 18, 18)
                .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1131, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manreserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manreserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manreserActionPerformed

    private void menusobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusobreActionPerformed
        // TODO add your handling code here:
        
    TelaSobre sobre = new TelaSobre();
    sobre.setVisible(true);
        
    }//GEN-LAST:event_menusobreActionPerformed

    private void mancadcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mancadcliActionPerformed
        // Chamando TelaCliente 
        
       TelaCliente cliente = new TelaCliente();
       cliente.setVisible(true);
       desktop.add(cliente);
    }//GEN-LAST:event_mancadcliActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // As linhas abaixo susbstiuem a label lbldata pela data actual do sistema ao inicilizar o form
        
        Date data= new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lbldata.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menOpcsaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpcsaiActionPerformed
    
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION);
        
        if(sair == JOptionPane.YES_OPTION){
        System.exit(0);
        }
        
    }//GEN-LAST:event_menOpcsaiActionPerformed

    private void mancadusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mancadusuActionPerformed
       TelaUsuario usuario = new TelaUsuario();
       
       usuario.setVisible(true);
       desktop.add(usuario);
        
        
        
    }//GEN-LAST:event_mancadusuActionPerformed

    private void mancadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mancadosActionPerformed
        // Chamando Tela OS
        TelaOs os = new TelaOs();
        os.setVisible(true);
        desktop.add(os);
    }//GEN-LAST:event_mancadosActionPerformed

    private void menrelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menrelActionPerformed
     
        
    }//GEN-LAST:event_menrelActionPerformed

    private void manRelcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manRelcliActionPerformed
        
          // Gerando um relatório de clientes;
        
        int confirma = JOptionPane.showConfirmDialog(null," Confirma a Impressão deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
       if(confirma== JOptionPane.YES_OPTION){
       // Imprimir relatório com o framework JasperReports 
       
           try {
               // Usando a classe JasperPrint psra preparar a impressao de um relaório 
               JasperPrint print =JasperFillManager.fillReport("C:\\Users\\Nelson Salvador\\JaspersoftWorkspace\\MyReports\\cliente.jasper",null, conexao);
               
               // A linha abaixo exibe o relatório através da classe JasperViewer
              JasperViewer.viewReport(print,false);
           } catch (Exception e) {
               JOptionPane.showConfirmDialog(null, e);
           }
       
       } 
       
       
       
    }                                        

    private void menrelAction(java.awt.event.ActionEvent evt) {   
        
    }//GEN-LAST:event_manRelcliActionPerformed

    private void mencadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mencadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lbldata;
    public static javax.swing.JLabel lblusuario;
    private javax.swing.JMenuItem manRelcli;
    private javax.swing.JMenuItem mancadcli;
    private javax.swing.JMenuItem mancados;
    public static javax.swing.JMenuItem mancadusu;
    private javax.swing.JMenuItem manreser;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenuItem menOpcsai;
    private javax.swing.JMenu menajusob;
    private javax.swing.JMenu mencad;
    public static javax.swing.JMenu menrel;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menusobre;
    // End of variables declaration//GEN-END:variables

}
